/**
 * Database Seeder
 * Run with: node src/seeds/seed.js
 */

require("dotenv").config();
const mongoose = require("mongoose");
const { mongodbUri } = require("../config/env");

// Models
const User = require("../models/user.model");
const Category = require("../models/category.model");
const SubCategory = require("../models/subcategory.model");
const Product = require("../models/product.model");
const Cart = require("../models/cart.model");
const Order = require("../models/order.model");
const Address = require("../models/address.model");

const seedDatabase = async () => {
  try {
    await mongoose.connect(mongodbUri);
    console.log("Connected to MongoDB");

    // Clear existing data
    await Promise.all([
      User.deleteMany({}),
      Category.deleteMany({}),
      SubCategory.deleteMany({}),
      Product.deleteMany({}),
      Cart.deleteMany({}),
      Order.deleteMany({}),
      Address.deleteMany({}),
    ]);
    console.log("Cleared existing data");

    // Create Admin User (passwordHash will be hashed by pre-save hook)
    await User.create({
      name: "Admin User",
      email: "admin@ecommerce.com",
      passwordHash: "admin123",
      role: "admin",
      isActive: true,
    });
    console.log("Created admin user: admin@ecommerce.com / admin123");

    // Create Test User (passwordHash will be hashed by pre-save hook)
    const testUser = await User.create({
      name: "Test User",
      email: "user@ecommerce.com",
      mobile: "01000000000",
      passwordHash: "user123",
      role: "user",
      isActive: true,
    });
    console.log("Created test user: user@ecommerce.com / user123");

    // Create Categories with images
    const menCategory = await Category.create({
      name: "Men",
      slug: "men",
      description: "Men's clothing and accessories",
      image:
        "https://images.unsplash.com/photo-1490578474895-699cd4e2cf59?w=400&h=400&fit=crop",
      isActive: true,
    });

    const womenCategory = await Category.create({
      name: "Women",
      slug: "women",
      description: "Women's clothing and accessories",
      image:
        "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=400&h=400&fit=crop",
      isActive: true,
    });
    console.log("Created categories");

    // Create Subcategories
    const menSubcategories = await SubCategory.insertMany([
      {
        name: "T-Shirts",
        slug: "t-shirts",
        categoryId: menCategory._id,
        isActive: true,
      },
      {
        name: "Jeans",
        slug: "jeans",
        categoryId: menCategory._id,
        isActive: true,
      },
      {
        name: "Shoes",
        slug: "shoes",
        categoryId: menCategory._id,
        isActive: true,
      },
      {
        name: "Jackets",
        slug: "jackets",
        categoryId: menCategory._id,
        isActive: true,
      },
      {
        name: "Shirts",
        slug: "shirts",
        categoryId: menCategory._id,
        isActive: true,
      },
    ]);

    const womenSubcategories = await SubCategory.insertMany([
      {
        name: "Dresses",
        slug: "dresses",
        categoryId: womenCategory._id,
        isActive: true,
      },
      {
        name: "Tops",
        slug: "tops",
        categoryId: womenCategory._id,
        isActive: true,
      },
      {
        name: "Bags",
        slug: "bags",
        categoryId: womenCategory._id,
        isActive: true,
      },
      {
        name: "Accessories",
        slug: "accessories",
        categoryId: womenCategory._id,
        isActive: true,
      },
      {
        name: "Shoes",
        slug: "women-shoes",
        categoryId: womenCategory._id,
        isActive: true,
      },
    ]);
    console.log("Created subcategories");

    // Men's Products - 35 items
    const menProducts = [
      {
        name: "Classic White Cotton T-Shirt",
        slug: "classic-white-cotton-tshirt",
        description: "A timeless classic white cotton t-shirt.",
        price: 29.99,
        images: [
          "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[0]._id,
        stock: 50,
        gender: "men",
        isBestSeller: true,
        isNewArrival: true,
      },
      {
        name: "Black Graphic Print T-Shirt",
        slug: "black-graphic-print-tshirt",
        description: "Bold graphic print t-shirt.",
        price: 34.99,
        images: [
          "https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[0]._id,
        stock: 30,
        gender: "men",
        isBestSeller: false,
        isNewArrival: true,
      },
      {
        name: "Navy Blue V-Neck T-Shirt",
        slug: "navy-blue-vneck-tshirt",
        description: "Elegant navy blue v-neck t-shirt.",
        price: 32.99,
        images: [
          "https://images.unsplash.com/photo-1562157873-818bc0726f68?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[0]._id,
        stock: 45,
        gender: "men",
        isBestSeller: true,
        isNewArrival: false,
      },
      {
        name: "Striped Polo T-Shirt",
        slug: "striped-polo-tshirt",
        description: "Classic striped polo shirt.",
        price: 44.99,
        images: [
          "https://images.unsplash.com/photo-1625910513413-5fc45bf84a3c?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[0]._id,
        stock: 35,
        gender: "men",
        isBestSeller: false,
        isNewArrival: true,
      },
      {
        name: "Grey Henley T-Shirt",
        slug: "grey-henley-tshirt",
        description: "Comfortable grey henley t-shirt.",
        price: 38.99,
        images: [
          "https://images.unsplash.com/photo-1618517351616-38fb9c5210c6?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[0]._id,
        stock: 28,
        gender: "men",
        isBestSeller: false,
        isNewArrival: false,
      },
      {
        name: "Red Cotton T-Shirt",
        slug: "red-cotton-tshirt",
        description: "Vibrant red cotton t-shirt.",
        price: 27.99,
        images: [
          "https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[0]._id,
        stock: 40,
        gender: "men",
        isBestSeller: false,
        isNewArrival: true,
      },
      {
        name: "Olive Green T-Shirt",
        slug: "olive-green-tshirt",
        description: "Casual olive green t-shirt.",
        price: 31.99,
        images: [
          "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[0]._id,
        stock: 38,
        gender: "men",
        isBestSeller: true,
        isNewArrival: false,
      },
      {
        name: "Long Sleeve Thermal Shirt",
        slug: "long-sleeve-thermal-shirt",
        description: "Warm thermal shirt for winter.",
        price: 42.99,
        images: [
          "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[0]._id,
        stock: 22,
        gender: "men",
        isBestSeller: false,
        isNewArrival: true,
      },
      {
        name: "Premium Cotton Tee Pack",
        slug: "premium-cotton-tee-pack",
        description: "3-pack premium cotton t-shirts.",
        price: 59.99,
        images: [
          "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[0]._id,
        stock: 50,
        gender: "men",
        isBestSeller: true,
        isNewArrival: false,
      },
      {
        name: "Vintage Wash T-Shirt",
        slug: "vintage-wash-tshirt",
        description: "Retro style vintage wash t-shirt.",
        price: 36.99,
        images: [
          "https://images.unsplash.com/photo-1523381294911-8d3cead13475?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[0]._id,
        stock: 25,
        gender: "men",
        isBestSeller: false,
        isNewArrival: true,
      },
      {
        name: "Relaxed Fit Cargo Jeans",
        slug: "relaxed-fit-cargo-jeans",
        description: "Comfortable cargo style jeans.",
        price: 79.99,
        images: [
          "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[1]._id,
        stock: 20,
        gender: "men",
        isBestSeller: true,
        isNewArrival: true,
      },
      {
        name: "Washed Grey Denim",
        slug: "washed-grey-denim",
        description: "Stylish washed grey jeans.",
        price: 67.99,
        images: [
          "https://images.unsplash.com/photo-1605518216938-7c31b7b14ad0?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[1]._id,
        stock: 28,
        gender: "men",
        isBestSeller: false,
        isNewArrival: true,
      },
      {
        name: "Tapered Fit Chinos",
        slug: "tapered-fit-chinos",
        description: "Smart casual tapered chinos.",
        price: 54.99,
        images: [
          "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[1]._id,
        stock: 35,
        gender: "men",
        isBestSeller: true,
        isNewArrival: false,
      },
      {
        name: "High Top Basketball Shoes",
        slug: "high-top-basketball-shoes",
        description: "Performance basketball shoes.",
        price: 139.99,
        images: [
          "https://images.unsplash.com/photo-1552346154-21d32810aba3?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[2]._id,
        stock: 18,
        gender: "men",
        isBestSeller: true,
        isNewArrival: true,
      },
      {
        name: "Classic Canvas Slip-Ons",
        slug: "classic-canvas-slipons",
        description: "Easy wear canvas slip-ons.",
        price: 49.99,
        images: [
          "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[2]._id,
        stock: 42,
        gender: "men",
        isBestSeller: false,
        isNewArrival: true,
      },
      {
        name: "Suede Desert Boots",
        slug: "suede-desert-boots",
        description: "Classic suede desert boots.",
        price: 99.99,
        images: [
          "https://images.unsplash.com/photo-1638247025967-b4e38f787b76?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[2]._id,
        stock: 15,
        gender: "men",
        isBestSeller: true,
        isNewArrival: false,
      },
      {
        name: "Quilted Winter Jacket",
        slug: "quilted-winter-jacket",
        description: "Warm quilted winter jacket.",
        price: 169.99,
        images: [
          "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[3]._id,
        stock: 14,
        gender: "men",
        isBestSeller: false,
        isNewArrival: true,
      },
      {
        name: "Lightweight Rain Jacket",
        slug: "lightweight-rain-jacket",
        description: "Waterproof rain jacket.",
        price: 79.99,
        images: [
          "https://images.unsplash.com/photo-1545594861-3bef43ff2fc8?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[3]._id,
        stock: 30,
        gender: "men",
        isBestSeller: true,
        isNewArrival: true,
      },
      {
        name: "Flannel Plaid Shirt",
        slug: "flannel-plaid-shirt",
        description: "Cozy flannel plaid shirt.",
        price: 52.99,
        images: [
          "https://images.unsplash.com/photo-1589310243389-96a5483213a8?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[4]._id,
        stock: 33,
        gender: "men",
        isBestSeller: false,
        isNewArrival: true,
      },
      {
        name: "Oxford Button Down",
        slug: "oxford-button-down",
        description: "Classic oxford button down shirt.",
        price: 58.99,
        images: [
          "https://images.unsplash.com/photo-1603252109303-2751441dd157?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[4]._id,
        stock: 45,
        gender: "men",
        isBestSeller: true,
        isNewArrival: false,
      },
      {
        name: "Slim Fit Dark Denim Jeans",
        slug: "slim-fit-dark-denim-jeans",
        description: "Modern slim fit jeans.",
        price: 69.99,
        images: [
          "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[1]._id,
        stock: 25,
        gender: "men",
        isBestSeller: true,
        isNewArrival: false,
      },
      {
        name: "Classic Blue Straight Jeans",
        slug: "classic-blue-straight-jeans",
        description: "Timeless classic blue jeans.",
        price: 64.99,
        images: [
          "https://images.unsplash.com/photo-1604176354204-9268737828e4?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[1]._id,
        stock: 40,
        gender: "men",
        isBestSeller: true,
        isNewArrival: true,
      },
      {
        name: "Black Skinny Jeans",
        slug: "black-skinny-jeans",
        description: "Sleek black skinny jeans.",
        price: 59.99,
        images: [
          "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[1]._id,
        stock: 32,
        gender: "men",
        isBestSeller: false,
        isNewArrival: true,
      },
      {
        name: "Distressed Vintage Jeans",
        slug: "distressed-vintage-jeans",
        description: "Trendy distressed jeans.",
        price: 74.99,
        images: [
          "https://images.unsplash.com/photo-1582552938357-32b906df40cb?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[1]._id,
        stock: 18,
        gender: "men",
        isBestSeller: false,
        isNewArrival: false,
      },
      {
        name: "White Urban Sneakers",
        slug: "white-urban-sneakers",
        description: "Stylish white urban sneakers.",
        price: 89.99,
        images: [
          "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[2]._id,
        stock: 22,
        gender: "men",
        isBestSeller: true,
        isNewArrival: true,
      },
      {
        name: "Black Leather Oxford Shoes",
        slug: "black-leather-oxford-shoes",
        description: "Classic black leather oxford shoes.",
        price: 129.99,
        images: [
          "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[2]._id,
        stock: 15,
        gender: "men",
        isBestSeller: true,
        isNewArrival: false,
      },
      {
        name: "Brown Casual Loafers",
        slug: "brown-casual-loafers",
        description: "Comfortable brown leather loafers.",
        price: 79.99,
        images: [
          "https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[2]._id,
        stock: 28,
        gender: "men",
        isBestSeller: false,
        isNewArrival: true,
      },
      {
        name: "Running Sports Shoes",
        slug: "running-sports-shoes",
        description: "High-performance running shoes.",
        price: 119.99,
        images: [
          "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[2]._id,
        stock: 35,
        gender: "men",
        isBestSeller: true,
        isNewArrival: true,
      },
      {
        name: "Black Leather Biker Jacket",
        slug: "black-leather-biker-jacket",
        description: "Iconic black leather biker jacket.",
        price: 199.99,
        images: [
          "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[3]._id,
        stock: 12,
        gender: "men",
        isBestSeller: true,
        isNewArrival: true,
      },
      {
        name: "Navy Blue Bomber Jacket",
        slug: "navy-blue-bomber-jacket",
        description: "Classic navy blue bomber jacket.",
        price: 149.99,
        images: [
          "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[3]._id,
        stock: 20,
        gender: "men",
        isBestSeller: false,
        isNewArrival: true,
      },
      {
        name: "Grey Hooded Windbreaker",
        slug: "grey-hooded-windbreaker",
        description: "Lightweight grey windbreaker.",
        price: 89.99,
        images: [
          "https://images.unsplash.com/photo-1544923246-77307dd628b8?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[3]._id,
        stock: 25,
        gender: "men",
        isBestSeller: false,
        isNewArrival: false,
      },
      {
        name: "Olive Green Parka Jacket",
        slug: "olive-green-parka-jacket",
        description: "Warm olive green parka jacket.",
        price: 179.99,
        images: [
          "https://images.unsplash.com/photo-1547949003-9792a18a2601?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[3]._id,
        stock: 8,
        gender: "men",
        isBestSeller: false,
        isNewArrival: false,
      },
      {
        name: "White Formal Dress Shirt",
        slug: "white-formal-dress-shirt",
        description: "Classic white formal dress shirt.",
        price: 54.99,
        images: [
          "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[4]._id,
        stock: 40,
        gender: "men",
        isBestSeller: true,
        isNewArrival: false,
      },
      {
        name: "Blue Checkered Casual Shirt",
        slug: "blue-checkered-casual-shirt",
        description: "Stylish blue checkered shirt.",
        price: 49.99,
        images: [
          "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[4]._id,
        stock: 35,
        gender: "men",
        isBestSeller: false,
        isNewArrival: true,
      },
      {
        name: "Denim Button-Up Shirt",
        slug: "denim-button-up-shirt",
        description: "Trendy denim button-up shirt.",
        price: 59.99,
        images: [
          "https://images.unsplash.com/photo-1588359348347-9bc6cbbb689e?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[4]._id,
        stock: 28,
        gender: "men",
        isBestSeller: true,
        isNewArrival: true,
      },
      {
        name: "Linen Summer Shirt",
        slug: "linen-summer-shirt",
        description: "Breathable linen shirt.",
        price: 64.99,
        images: [
          "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400&h=500&fit=crop",
        ],
        categoryId: menCategory._id,
        subCategoryId: menSubcategories[4]._id,
        stock: 22,
        gender: "men",
        isBestSeller: false,
        isNewArrival: false,
      },
    ];

    // Women's Products - 35 items
    const womenProducts = [
      {
        name: "Floral Summer Maxi Dress",
        slug: "floral-summer-maxi-dress",
        description: "Beautiful floral print summer maxi dress.",
        price: 79.99,
        images: [
          "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[0]._id,
        stock: 25,
        gender: "women",
        isBestSeller: true,
        isNewArrival: true,
      },
      {
        name: "Elegant Black Evening Dress",
        slug: "elegant-black-evening-dress",
        description: "Stunning black evening dress.",
        price: 149.99,
        images: [
          "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[0]._id,
        stock: 15,
        gender: "women",
        isBestSeller: true,
        isNewArrival: false,
      },
      {
        name: "Red Cocktail Dress",
        slug: "red-cocktail-dress",
        description: "Eye-catching red cocktail dress.",
        price: 119.99,
        images: [
          "https://images.unsplash.com/photo-1518622358385-8ea7d0794bf6?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[0]._id,
        stock: 18,
        gender: "women",
        isBestSeller: false,
        isNewArrival: true,
      },
      {
        name: "Casual Denim Shirt Dress",
        slug: "casual-denim-shirt-dress",
        description: "Comfortable denim shirt dress.",
        price: 69.99,
        images: [
          "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[0]._id,
        stock: 30,
        gender: "women",
        isBestSeller: false,
        isNewArrival: false,
      },
      {
        name: "Bohemian Wrap Dress",
        slug: "bohemian-wrap-dress",
        description: "Flowing bohemian wrap dress.",
        price: 89.99,
        images: [
          "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[0]._id,
        stock: 22,
        gender: "women",
        isBestSeller: true,
        isNewArrival: true,
      },
      {
        name: "White Lace Summer Dress",
        slug: "white-lace-summer-dress",
        description: "Delicate white lace summer dress.",
        price: 94.99,
        images: [
          "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[0]._id,
        stock: 20,
        gender: "women",
        isBestSeller: false,
        isNewArrival: true,
      },
      {
        name: "Navy Blue Midi Dress",
        slug: "navy-blue-midi-dress",
        description: "Elegant navy blue midi dress.",
        price: 85.99,
        images: [
          "https://images.unsplash.com/photo-1485231183945-fffde7f10eb9?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[0]._id,
        stock: 24,
        gender: "women",
        isBestSeller: true,
        isNewArrival: false,
      },
      {
        name: "Polka Dot Vintage Dress",
        slug: "polka-dot-vintage-dress",
        description: "Retro polka dot vintage dress.",
        price: 72.99,
        images: [
          "https://images.unsplash.com/photo-1502716119720-b23a93e5fe1b?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[0]._id,
        stock: 16,
        gender: "women",
        isBestSeller: false,
        isNewArrival: true,
      },
      {
        name: "Emerald Green Party Dress",
        slug: "emerald-green-party-dress",
        description: "Stunning emerald green party dress.",
        price: 135.99,
        images: [
          "https://images.unsplash.com/photo-1568252542512-9fe8fe9c87bb?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[0]._id,
        stock: 12,
        gender: "women",
        isBestSeller: true,
        isNewArrival: true,
      },
      {
        name: "Floral Print Blouse",
        slug: "floral-print-blouse",
        description: "Beautiful floral print blouse.",
        price: 48.99,
        images: [
          "https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[1]._id,
        stock: 38,
        gender: "women",
        isBestSeller: false,
        isNewArrival: true,
      },
      {
        name: "Satin Cami Top",
        slug: "satin-cami-top",
        description: "Luxurious satin cami top.",
        price: 36.99,
        images: [
          "https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[1]._id,
        stock: 42,
        gender: "women",
        isBestSeller: true,
        isNewArrival: false,
      },
      {
        name: "Knit Sweater Top",
        slug: "knit-sweater-top",
        description: "Cozy knit sweater top.",
        price: 55.99,
        images: [
          "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[1]._id,
        stock: 30,
        gender: "women",
        isBestSeller: false,
        isNewArrival: true,
      },
      {
        name: "Peplum Formal Top",
        slug: "peplum-formal-top",
        description: "Elegant peplum formal top.",
        price: 52.99,
        images: [
          "https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[1]._id,
        stock: 25,
        gender: "women",
        isBestSeller: true,
        isNewArrival: true,
      },
      {
        name: "Quilted Designer Bag",
        slug: "quilted-designer-bag",
        description: "Classic quilted designer bag.",
        price: 189.99,
        images: [
          "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[2]._id,
        stock: 10,
        gender: "women",
        isBestSeller: true,
        isNewArrival: true,
      },
      {
        name: "Woven Straw Beach Bag",
        slug: "woven-straw-beach-bag",
        description: "Summer woven straw beach bag.",
        price: 39.99,
        images: [
          "https://images.unsplash.com/photo-1523779917675-b6ed3a42a561?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[2]._id,
        stock: 35,
        gender: "women",
        isBestSeller: false,
        isNewArrival: true,
      },
      {
        name: "Mini Backpack Purse",
        slug: "mini-backpack-purse",
        description: "Trendy mini backpack purse.",
        price: 65.99,
        images: [
          "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[2]._id,
        stock: 28,
        gender: "women",
        isBestSeller: true,
        isNewArrival: false,
      },
      {
        name: "Statement Necklace",
        slug: "statement-necklace",
        description: "Bold statement necklace.",
        price: 45.99,
        images: [
          "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[3]._id,
        stock: 40,
        gender: "women",
        isBestSeller: false,
        isNewArrival: true,
      },
      {
        name: "Pearl Drop Earrings",
        slug: "pearl-drop-earrings",
        description: "Elegant pearl drop earrings.",
        price: 55.99,
        images: [
          "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[3]._id,
        stock: 45,
        gender: "women",
        isBestSeller: true,
        isNewArrival: true,
      },
      {
        name: "Cashmere Wrap Shawl",
        slug: "cashmere-wrap-shawl",
        description: "Luxurious cashmere wrap shawl.",
        price: 129.99,
        images: [
          "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[3]._id,
        stock: 18,
        gender: "women",
        isBestSeller: false,
        isNewArrival: false,
      },
      {
        name: "Leather Watch",
        slug: "leather-watch-women",
        description: "Classic leather strap watch.",
        price: 89.99,
        images: [
          "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[3]._id,
        stock: 22,
        gender: "women",
        isBestSeller: true,
        isNewArrival: true,
      },
      {
        name: "Block Heel Sandals",
        slug: "block-heel-sandals",
        description: "Comfortable block heel sandals.",
        price: 79.99,
        images: [
          "https://images.unsplash.com/photo-1562273138-f46be4ebdf33?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[4]._id,
        stock: 30,
        gender: "women",
        isBestSeller: false,
        isNewArrival: true,
      },
      {
        name: "Pointed Toe Flats",
        slug: "pointed-toe-flats",
        description: "Elegant pointed toe flats.",
        price: 54.99,
        images: [
          "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[4]._id,
        stock: 38,
        gender: "women",
        isBestSeller: true,
        isNewArrival: false,
      },
      {
        name: "Espadrille Wedges",
        slug: "espadrille-wedges",
        description: "Summer espadrille wedge sandals.",
        price: 69.99,
        images: [
          "https://images.unsplash.com/photo-1596484552834-6a58f850e0a1?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[4]._id,
        stock: 24,
        gender: "women",
        isBestSeller: false,
        isNewArrival: true,
      },
      {
        name: "White Silk Blouse",
        slug: "white-silk-blouse",
        description: "Elegant white silk blouse.",
        price: 64.99,
        images: [
          "https://images.unsplash.com/photo-1551163943-3f6a855d1153?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[1]._id,
        stock: 35,
        gender: "women",
        isBestSeller: true,
        isNewArrival: false,
      },
      {
        name: "Striped Crop Top",
        slug: "striped-crop-top",
        description: "Trendy striped crop top.",
        price: 29.99,
        images: [
          "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[1]._id,
        stock: 45,
        gender: "women",
        isBestSeller: false,
        isNewArrival: true,
      },
      {
        name: "Off-Shoulder Ruffle Top",
        slug: "off-shoulder-ruffle-top",
        description: "Romantic off-shoulder top.",
        price: 44.99,
        images: [
          "https://images.unsplash.com/photo-1485968579169-a6f4a7d4b2f4?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[1]._id,
        stock: 28,
        gender: "women",
        isBestSeller: true,
        isNewArrival: true,
      },
      {
        name: "Basic Black Tank Top",
        slug: "basic-black-tank-top",
        description: "Essential black tank top.",
        price: 19.99,
        images: [
          "https://images.unsplash.com/photo-1503342394128-c104d54dba01?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[1]._id,
        stock: 60,
        gender: "women",
        isBestSeller: true,
        isNewArrival: false,
      },
      {
        name: "Brown Leather Tote Bag",
        slug: "brown-leather-tote-bag",
        description: "Premium brown leather tote bag.",
        price: 159.99,
        images: [
          "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[2]._id,
        stock: 12,
        gender: "women",
        isBestSeller: true,
        isNewArrival: true,
      },
      {
        name: "Black Crossbody Bag",
        slug: "black-crossbody-bag",
        description: "Compact black crossbody bag.",
        price: 79.99,
        images: [
          "https://images.unsplash.com/photo-1591561954555-607968c989ab?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[2]._id,
        stock: 25,
        gender: "women",
        isBestSeller: false,
        isNewArrival: true,
      },
      {
        name: "Beige Canvas Shoulder Bag",
        slug: "beige-canvas-shoulder-bag",
        description: "Casual beige canvas shoulder bag.",
        price: 49.99,
        images: [
          "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[2]._id,
        stock: 30,
        gender: "women",
        isBestSeller: false,
        isNewArrival: false,
      },
      {
        name: "Gold Chain Clutch",
        slug: "gold-chain-clutch",
        description: "Elegant clutch with gold chain strap.",
        price: 89.99,
        images: [
          "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[2]._id,
        stock: 15,
        gender: "women",
        isBestSeller: true,
        isNewArrival: false,
      },
      {
        name: "Gold Hoop Earrings",
        slug: "gold-hoop-earrings",
        description: "Classic gold hoop earrings.",
        price: 39.99,
        images: [
          "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[3]._id,
        stock: 50,
        gender: "women",
        isBestSeller: true,
        isNewArrival: true,
      },
      {
        name: "Silk Printed Scarf",
        slug: "silk-printed-scarf",
        description: "Luxurious silk scarf.",
        price: 59.99,
        images: [
          "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[3]._id,
        stock: 35,
        gender: "women",
        isBestSeller: false,
        isNewArrival: true,
      },
      {
        name: "Wide Brim Sun Hat",
        slug: "wide-brim-sun-hat",
        description: "Stylish wide brim hat.",
        price: 44.99,
        images: [
          "https://images.unsplash.com/photo-1521369909029-2afed882baee?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[3]._id,
        stock: 25,
        gender: "women",
        isBestSeller: true,
        isNewArrival: false,
      },
      {
        name: "Leather Belt with Gold Buckle",
        slug: "leather-belt-gold-buckle",
        description: "Premium leather belt.",
        price: 54.99,
        images: [
          "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[3]._id,
        stock: 40,
        gender: "women",
        isBestSeller: false,
        isNewArrival: false,
      },
      {
        name: "Nude High Heel Pumps",
        slug: "nude-high-heel-pumps",
        description: "Classic nude high heel pumps.",
        price: 99.99,
        images: [
          "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[4]._id,
        stock: 20,
        gender: "women",
        isBestSeller: true,
        isNewArrival: true,
      },
      {
        name: "White Canvas Sneakers",
        slug: "white-canvas-sneakers-women",
        description: "Comfortable white canvas sneakers.",
        price: 59.99,
        images: [
          "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[4]._id,
        stock: 35,
        gender: "women",
        isBestSeller: true,
        isNewArrival: false,
      },
      {
        name: "Black Ankle Boots",
        slug: "black-ankle-boots-women",
        description: "Versatile black ankle boots.",
        price: 119.99,
        images: [
          "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[4]._id,
        stock: 18,
        gender: "women",
        isBestSeller: false,
        isNewArrival: true,
      },
      {
        name: "Strappy Flat Sandals",
        slug: "strappy-flat-sandals",
        description: "Comfortable strappy flat sandals.",
        price: 49.99,
        images: [
          "https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400&h=500&fit=crop",
        ],
        categoryId: womenCategory._id,
        subCategoryId: womenSubcategories[4]._id,
        stock: 42,
        gender: "women",
        isBestSeller: false,
        isNewArrival: false,
      },
    ];

    // Insert all products
    await Product.insertMany([...menProducts, ...womenProducts]);
    console.log(
      "Created " + (menProducts.length + womenProducts.length) + " products",
    );

    // Create a sample address for test user
    const testAddress = await Address.create({
      userId: testUser._id,
      label: "Home",
      city: "Cairo",
      area: "Maadi",
      street: "123 Main Street",
      building: "Block A, Apt 15",
      notes: "Near the mall",
      isDefault: true,
    });

    // Create a sample order for test user
    const sampleProduct = await Product.findOne({
      gender: "men",
      stock: { $gt: 0 },
    });
    await Order.create({
      orderNumber: "ORD-" + Date.now() + "-TEST",
      userId: testUser._id,
      customerSnapshot: {
        name: testUser.name,
        email: testUser.email,
        mobile: testUser.mobile,
      },
      addressSnapshot: {
        label: testAddress.label,
        city: testAddress.city,
        area: testAddress.area,
        street: testAddress.street,
        building: testAddress.building,
        notes: testAddress.notes,
      },
      items: [
        {
          productId: sampleProduct._id,
          productName: sampleProduct.name,
          productImage: sampleProduct.images[0],
          quantity: 2,
          price: sampleProduct.price,
          total: sampleProduct.price * 2,
        },
      ],
      subtotal: sampleProduct.price * 2,
      shippingCost: 0,
      total: sampleProduct.price * 2,
      status: "pending",
      statusHistory: [{ status: "pending", changedAt: new Date() }],
    });
    console.log("Created sample order for test user");

    // Add items to test user's cart
    await Cart.create({
      userId: testUser._id,
      items: [
        {
          productId: sampleProduct._id,
          productName: sampleProduct.name,
          productImage: sampleProduct.images[0],
          quantity: 1,
          priceAtAdd: sampleProduct.price,
        },
      ],
    });
    console.log("Created cart with items for test user");

    console.log("\n✅ Database seeded successfully!\n");
    console.log("Admin Login:");
    console.log("  Email: admin@ecommerce.com");
    console.log("  Password: admin123\n");
    console.log("User Login:");
    console.log("  Email: user@ecommerce.com");
    console.log("  Password: user123\n");
    console.log(
      "Total Products: " + (menProducts.length + womenProducts.length),
    );

    process.exit(0);
  } catch (error) {
    console.error("Seeding error:", error);
    process.exit(1);
  }
};

seedDatabase();
